export const OFFLINE_KEY = 'offline'
export const OFFLINE_PRIORITY_KEY = 'offlinePriority'
export const TOKEN_KEY = 'token'
export const SESSION_ID_KEY = 'sessionId'
export const AUTH_WAITING_KEY = 'authWaiting'
export const DB_VERSION_KEY = 'DBVersion'
export const VOLUME_KEY = 'audioVolume'
